### ISSUE TITLE
CI fail

### ISSUE THREAD

**Issue by madwort** [opensafely-core/sysadmin#75]
https://github.com/opensafely-core/sysadmin/actions/runs/3190280862/jobs/5205166024

```
Run echo "WARNING: ignore output from this command - it is running w/o elevated privileges needed to correctly read branch protection details"
WARNING: ignore output from this command - it is running w/o elevated privileges needed to correctly read branch protection details
*** DRY RUN - no changes will be made ***
Traceback (most recent call last):
  File "manage-github.py", line 307, in <module>
    main()
  File "manage-github.py", line 259, in main
    studies = client.get_org('opensafely')
  File "/home/runner/work/sysadmin/sysadmin/client.py", line 22, in get_org
    return github_client().get_organization(org)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/github/MainClass.py", line 296, in get_organization
    headers, data = self.__requester.requestJsonAndCheck("GET", f"/orgs/{login}")
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
Error: Process completed with exit code 1.
```

**Comment by madwort** [comment]
the read-only token used to run this test has expired

**Comment by bloodearnest** [comment]
have updated token, should be fixed
